### ISSUE TITLE
Support splines of degree 0

### ISSUE THREAD

**Issue by yguclu** [pyccel/psydac#175]
For certain applications it is useful to work with piecewise constant polynomials. To this end we should make sure that the functions in `core/bsplines.py` support splines of degree `p=0` (currently `p>=1` is required).

**Comment by yguclu** [comment]
@e-moral-sanchez Was this issue closed by PR #250?

**Comment by e-moral-sanchez** [comment]
Yes, Splines of degree 1 can be used
