### ISSUE TITLE
Pyccelise `kernels.py` and `bsplines_pyccel.py` automatically when installing psydac.

### ISSUE THREAD

**Issue by anlavandier** [pyccel/psydac#202]
Now that there are files which are meant to be accelerated with `pyccel`, we should find a way to automatically pyccelise them in `setup.py`.

**Comment by yguclu** [comment]
Like issue #268, this is indeed very important if we want to accelerate the unit tests.

**Comment by tomcaruso** [comment]
This issue should be solved by the PR #305

**Comment by tomcaruso** [comment]
Issue solved by merging PR #305
