### ISSUE TITLE
Do not update ghost regions in `DirectionalDerivativeOperator.dot()`

### ISSUE THREAD

**Issue by yguclu** [pyccel/psydac#242]
The method `dot` of class `DirectionalDerivativeOperator` always updates the ghost regions along the derivative direction. This is unnecessary and inefficient. Instead we should only check if the ghost regions are up to date and raise an error if not.

**Comment by tomcaruso** [comment]
Does this issue still relevant ? It seems that this issue has been solved : 

```
def dot(self, v, out=None):

        # setup, space checks
        assert v.space is self._domain

        # Check if the ghost regions are up to date
        if not v.ghost_regions_in_sync:
            v.update_ghost_regions()

        if out is None:
            out = self._codomain.zeros()
        
        assert isinstance(out, StencilVector)
        assert out.space is self._codomain

        # apply the differentiation and return the result
        self._do_diff(v, out)

        return out

```
In the code, if the ghost region is not up to date, it doesn't raise an error but update all the ghost region.

**Comment by yguclu** [comment]
@saidctb Can you confirm that the issue was resolved?

**Comment by saidctb** [comment]
> @saidctb Can you confirm that the issue was resolved?

Yes, this was resolved
