### ISSUE TITLE
Massive memory consumption with consecutive dot products

### ISSUE THREAD

**Issue by flohol** [pyccel/psydac#270]
When I do multiple matrix-vector products one after the other (e.g. in a for loop) my machine eventually hangs up because of a massive memory accumulation. After running the code

```
for i in range(10000):
    x = A.dot(b)
```

for `A` being a diagonal `BlockMatrix` of shape `(1536, 1536)` and `b` some `BlockVector` I have a memory consumption of about 2.5 GB. Making the loop even longer eventually leads to a system hang up.

**Comment by yguclu** [comment]
See #261 which has been mentioned in multiple meetings for the last two months.

**Comment by yguclu** [comment]
Possibly also related to #263.

**Comment by flohol** [comment]
Yes, indeed. Just checked and it occurs only for block operators

**Comment by yguclu** [comment]
@flohol Could you provide a (complete) minimal script which we will run manually to check the memory usage in the future?
