### ISSUE TITLE
Package inconsistency between sympde and psydac

### ISSUE THREAD

**Issue by spossann** [pyccel/psydac#280]
Psydac's `setup.py` says `'sympy>=1.5'`, while `sympde` requires `sympy<1.7,>=1.2`. A psydac install on my machine fetches `sympy-1.11.1-py3-none-any.whl` at the moment, which yields a consistency error.

**Comment by yguclu** [comment]
Duplicate of issue #225? Please read [this comment](https://github.com/pyccel/psydac/issues/225#issuecomment-1421156538).
