### ISSUE TITLE
Require a preconditioner to be a `LinearOperator`

### ISSUE THREAD

**Issue by yguclu** [pyccel/psydac#343]
The `PConjugateGradient` class represents the "preconditioned conjugate gradient" algorithm. It has the argument `pc` which represents the preconditioner.

Currently accepted values of `pc` are either a string with value `"jacobi"`, or a lambda function with arguments `(r, out)` which writes the action of the preconditioner on the vector `r` into the vector `out`. In the former case the class method `InverseLinearOperator.jacobi` is used, which also has arguments `(r, out)`. This approach is confusing and can be replaced by the accurate use of `LinearOperator` objects.

To do
------

- [ ] Only accept `None` or `LinearOperator` objects as values of the parameter `pc` of `PConjugateGradient.__init__`
- [ ] Remove the class method `InverseLinearOperator.jacobi`, and provide instead the class `Jacobi` as subclass of `LinearOperator`. The constructor of `Jacobi` requires an object of type `StencilMatrix`, or a `BlockLinearOperator` which has `StencilMatrix` objects on the main diagonal.

**Comment by axcheiste-rooney-mara** [comment]
hi yuyu its a rikuysa
