### ISSUE TITLE
Why does IdentityOperator return a BlockLinearOperator in case of BlockVectorSpace?

### ISSUE THREAD

**Issue by spossann** [pyccel/psydac#356]
```
class IdentityOperator(LinearOperator):

    def __new__(cls, domain, codomain=None):

        assert isinstance(domain, VectorSpace)
        if codomain:
            assert isinstance(codomain, VectorSpace)
            assert domain == codomain

        from psydac.linalg.block import BlockVectorSpace, BlockLinearOperator
        if isinstance(domain, BlockVectorSpace):
            spaces = domain.spaces
            blocks = {}
            for i, V in enumerate(spaces):
                blocks[i,i] = IdentityOperator(V)
            return BlockLinearOperator(domain, domain, blocks)
        else:
            return super().__new__(cls)
```
This is inconvenient to have a change of type depending on the vector space, especially when checking for the IdentityOperator in `assert` statements. I propose to remove this and always return an `IdentityOperator`.

**Comment by yguclu** [comment]
This is a design choice.

A `LinearOperator` acting on a `BlockVectorSpace` (either as the domain or the codomain) is always a `BlockLinearOperator`. This has to apply to the `IdentityOperator` as well, in order to avoid lots of corner cases. In particular, if we add a `BlockLinearOperator` to an `IdentityOperator` we should obtain another `BlockLinearOperator`.

E.g.:
```
[A    B]          [A    B]     [I    0]     [A + I  0]
[      ]  +  Id = [      ]  +  [      ]  +  [        ]
[C    D]          [C    D]     [0    I]     [0  A + I]
```

**Comment by spossann** [comment]
At the moment, in the [addition of `BlockLinearOperator`](https://github.com/pyccel/psydac/blob/535717c6f5ea328aacbbbbcc2d582a92b31c9377/psydac/linalg/block.py#L709), this behavior is not enforced: 
```
    def __add__(self, M):
        if not isinstance(M, BlockLinearOperator):
            return LinearOperator.__add__(self, M)
```
It seems thus you can get a `SumLinearOperator` back after addition. I would prefer this with respect to composition: because with `IdentityOperator(V0) @ StencilMatrix` we get back a `StencilMatrix`, whereas with `IdentityOperator(V1) @ BlockLinearOperator` we getback a `ComposedLinearOperator`. I understand however the idea of the design choice, but it does not seem to be enforced.

**Comment by yguclu** [comment]
We may need to add some tests and verify that things work as expected.

CC: @jowezarek
