### ISSUE TITLE
Accelerate computationally intensive operations using different backends

### ISSUE THREAD

**Issue by saidctb** [pyccel/psydac#78]
Accelerate the following operations:
- Method `dot` of `StencilMatrix`
- Method `dot` of `StencilVector`
- Method `transpose` of `StencilMatrix`
- Field evaluation

Using one of the available backends:
- Pyccel
- Numba

**Comment by ratnania** [comment]
Would it be possible to call BLAS with band matrices?

**Comment by yguclu** [comment]
> Would it be possible to call BLAS with band matrices?

@ratnania It may be possible in 1D. For higher-dimensional StencilMatrix objects the data structure is not compatible.

**Comment by yguclu** [comment]
Closed after #156 and #163
