### ISSUE TITLE
EvalField is not correct

### ISSUE THREAD

**Issue by ratnania** [pyccel/psydac#85]
This issue is related to #84 
An appropriate way to fix this is to make **LengthDofTest** work directly on the space and not the field or test/trial function. It is important to gather all fields that are on the same function space and do the evaluation on the quadrature points. 
By doing this, we will avoid also having variables (in the printed code) such as **span_F_1**, **test_F_p1** etc if **F** is a field.

So actualy, the **EvalField** works fine when we want to evaluate the norm, because we only have one field. We need to make it more general.

**Comment by saidctb** [comment]
the problem with EvalField are:
 - it only works with one field
 - the fields are not grouped by space
 the first problem is a bug, the second one is an optimisation.
 we can probably focus on the first one first
